#!/usr/bin/env sh
##############################################################################
# Gradle start up script for UN*X
#
# Generated by the Gradle wrapper
##############################################################################

DEFAULT_JVM_OPTS=""

APP_NAME="" 
APP_BASE_NAME=$(basename "$0")

# Allow this script to be run from any directory
PRG="$0"
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' >/dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")"/"$link
  fi
done

PRG_DIR=$(dirname "$PRG")
ROOT_DIR=$(cd "$PRG_DIR/.." >/dev/null; pwd)

CLASSPATH="$ROOT_DIR/gradle/wrapper/gradle-wrapper.jar"

if [ -z "$JAVA_HOME" ]; then
  java_exec="java"
else
  java_exec="$JAVA_HOME/bin/java"
fi

exec "$java_exec" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
