@echo off
REM ------------------------------------------------------------------------------
REM Gradle start up script for Windows
REM Generated by the Gradle wrapper
REM ------------------------------------------------------------------------------
setlocal













endlocal"%JAVA_EXE%" %DEFAULT_JVM_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*:executeset JAVA_EXE=java:findJavaFromPathgoto executeset JAVA_EXE=%JAVA_HOME%\bin\java.exe
n if not defined JAVA_HOME goto findJavaFromPathset CLASSPATH=%ROOT_DIR%\gradle\wrapper\gradle-wrapper.jarset ROOT_DIR=%SCRIPT_DIR%..set SCRIPT_DIR=%~dp0:: Determine script location